version: 0.2
env:
  variables:
    CI: "true"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install yarn
  build:
    commands:
      - yarn test
      - yarn build
artifacts:
  # discard-paths: yes
  files:
    - "cloudformation.template.yml"
    - "parameters/*"
    - "build/**/*"