AWSTemplateFormatVersion: "2010-09-09"
Description: Pipeline for Product Service
Parameters:
  RepoToken:
    Type: String
    NoEcho: true
    Description: OAuth Token for the github repository
Resources:
  ArtifactStorage:
    Type: "AWS::S3::Bucket"
  PipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "codebuild.amazonaws.com"
          - Effect: "Allow" 
            Action: "sts:AssumeRole"
            Principal:
              Service: "codepipeline.amazonaws.com"
          - Effect: "Allow" 
            Action: "sts:AssumeRole"
            Principal:
              Service: "cloudformation.amazonaws.com"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  # container
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      #This is the role that the build will execute as. If your build needs to pull artifacts from S3 or reach out of its container for any reason make sure this role has the permissions to do so.
      ServiceRole: !GetAtt PipelineRole.Arn 
      Source:
        #Where our sourcecode will come from (This special keyword says that CodePipeline will provide it)
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
      Artifacts:
        #Send any output back to code pipeline
        Type: CODEPIPELINE
  Pipeline:
    #This is the "Pipeline" or order flow of execution.
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - BuildProject
    Properties:
      ArtifactStore:
        Type: "S3"
        Location: !Ref ArtifactStorage
      RoleArn: !GetAtt PipelineRole.Arn
      RestartExecutionOnUpdate: true
      Stages: 
          #The first step triggers with changes in Github
        - Name: Source
          Actions:
          - Name: Source
            ActionTypeId:
              Category: Source
              Provider: GitHub
              Owner: ThirdParty
              Version: 1
            OutputArtifacts:
              - Name: sourceCode
            Configuration:
              Owner: "kfodex01" #Update this with your github username
              Repo: "roll-for-the-galaxy-react" #The repository to checkout
              Branch: deployment
              OAuthToken: !Ref RepoToken
          #Step two is to build the project using our configured CodeBuild project above.
        - Name: Build
          Actions:
          - Name: Build
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            InputArtifacts:
              - Name: sourceCode
            Configuration:
              ProjectName: !Ref BuildProject
            OutputArtifacts:
              - Name: buildResults
        - Name: Deploy_DEV
          Actions:
          - Name: Deploy
            RoleArn: !GetAtt PipelineRole.Arn
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: buildResults
            Configuration:
              #this is the name of the stack
              StackName: RollForTheGalaxy-DEV 
              #becuase this is dev, if the deploy fails on the first create, just destroy it rather than getting stuck in CREATE_FAILED state
              ActionMode: REPLACE_ON_FAILURE 
              #this special syntax represents the file we put in our "artifacts" section of the buildspec.yml
              TemplatePath: buildResults::cloudformation.template.yml
              TemplateConfiguration: buildResults::dev.params.json
              RoleArn: !GetAtt PipelineRole.Arn
              Capabilities: CAPABILITY_IAM
          - Name: DeploySite
            RoleArn: !GetAtt PipelineRole.Arn
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: S3
              Version: 1
            InputArtifacts:
              - Name: buildResults
            Configuration:
              BucketName: rftg.dev.austincreations.net
              Extract: true
              ObjectKey: 'build/**/*'
          #This is the same as the stage above except the StackName, ActionMode and TemplateConfiguration are different
        - Name: Deploy_PROD
          Actions:
          - Name: Deploy
            RoleArn: !GetAtt PipelineRole.Arn
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: buildResults
            Configuration:
              StackName: RollForTheGalaxy-PROD 
              #Create or update the stack, but don't delete it if it fails
              ActionMode: CREATE_UPDATE 
              TemplatePath: buildResults::cloudformation.template.yml
              TemplateConfiguration: buildResults::prod.params.json
              RoleArn: !GetAtt PipelineRole.Arn
              Capabilities: CAPABILITY_IAM
Outputs:
  PipelineRoleARN:
    Value: !GetAtt PipelineRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-PipelineRoleARN
