export const tileTypes = {
    BLUE_WORLD: 'Blue World',
    BROWN_WORLD: 'Brown World',
    DEVELOPMENT: 'Development',
    GRAY_WORLD: 'Gray World',
    GREEN_WORLD: 'Green World',
    YELLOW_WORLD: 'Yellow World'
};

export const phases = {
    ASSIGNMENT: 'Assignment',
    DEVELOP: 'Develop',
    ENDGAME: 'EndGame',
    EXPLORE: 'Explore',
    PRODUCE: 'Produce',
    SETTLE: 'Settle',
    SHIP: 'Ship'
};

export const dieColor = {
    BLUE: 'Blue',
    BROWN: 'Brown',
    GREEN: 'Green',
    PURPLE: 'Purple',
    RED: 'Red',
    WHITE: 'White',
    YELLOW: 'Yellow'
};

export const dieFace = {
    DEVELOP: 'Develop',
    EXPLORE: 'Explore',
    PRODUCE: 'Produce',
    SETTLE: 'Settle',
    SHIP: 'Ship',
    WILD: 'Wild'
};

export const gameColors = {
    BLACK: '#000000',
    BLUE: '#00aadd',
    BROWN: '#8b4513',
    GRAY: '#808080',
    GREEN: '#008000',
    PURPLE: '#dd50dd',
    RED: '#ff2020',
    WHITE: '#ffffff',
    YELLOW: '#dddd00'
};

export const bonuses = {
    CONSCRIPTION: 'Remove any one of your dice, then gain two Military (red) dice into your cup.',
    EIGHT_CREDITS: 'Begin the game with $8 instead of $1.',
    INFORMATION_TECH: 'Remove any one of your dice, then gain two Novelty (blue) dice into your cup.',
    ONE_BLUE_DIE_TO_CITIZENRY: 'Gain a Novelty (blue) die into your Citizenry when you place this world.',
    ONE_BLUE_DIE_TO_CUP: 'Gain a Novelty (blue) die into your cup when you place this world.',
    ONE_BLUE_DIE_TO_WORLD: 'Gain a Novelty (blue) good on this world when you place it.',
    ONE_BLUE_DIE_AND_ONE_RED_DIE_TO_CITIZENRY: 'Gain a Novelty (blue) die and a Military (red) into your Citizenry when you place this world.',
    ONE_BROWN_DIE_AND_ONE_RED_DIE_TO_CITIZENRY: 'Gain a Military (red) die and a Rare Elements (brown) die into your Citizenry when you place this world.',
    ONE_BROWN_DIE_TO_CUP: 'Gain a Rare Elements (brown) die into your cup when you place this world.',
    ONE_BROWN_DIE_TO_CITIZENRY: 'Gain a Rare Elements (brown) die into your Citizenry when you place this world.',
    ONE_BROWN_DIE_TO_WORLD: 'Gain a Rare Elements (brown) good on this world when you place it.',
    ONE_CREDIT_AND_ONE_BROWN_DIE_TO_WORLD: 'Gain $1 and a Rare Elements (brown) good on this world when you place it.',
    ONE_CREDIT_AND_ONE_GREEN_DIE_TO_CUP: 'Gain $1 and a Genes (green) die into your cup when you place this world.',
    ONE_CREDIT_AND_ONE_GREEN_DIE_TO_WORLD: 'Gain $1 and a Genes (green) good on this world when you place it.',
    ONE_CREDIT_AND_ONE_PURPLE_DIE_TO_CITIZENRY: 'Gain $1 and a Consumption (purple) die into your Citizenry when you place this world.',
    ONE_CREDIT_AND_ONE_YELLOW_DIE_TO_CUP: 'Gain $1 and a Alien Technology (yellow) die into your cup when you place this world.',
    ONE_CREDIT_AND_ONE_YELLOW_DIE_TO_WORLD: 'Gain $1 and a Alien Technology (yellow) good on this world when you place it.',
    ONE_GREEN_DIE_TO_CUP: 'Gain a Genes (green) die into your cup when you place this world.',
    ONE_GREEN_DIE_TO_CITIZENRY: 'Gain a Genes (green) die into your Citizenry when you place this world.',
    ONE_GREEN_DIE_TO_WORLD: 'Gain a Genes (green) good on this world when you place it.',
    ONE_PURPLE_DIE_TO_CITIZENRY: 'Gain a Consumption (purple) die into your Citizenry when you place this world.',
    ONE_PURPLE_DIE_TO_CUP: 'Gain a Consumption (purple) die into your cup when you place this world.',
    ONE_RED_DIE_TO_CITIZENRY: 'Gain a Military (red) die into your Citizenry when you place this world.',
    ONE_RED_DIE_TO_CUP: 'Gain a Military (red) die into your cup when you place this world.',
    ONE_YELLOW_DIE_TO_CITIZENRY: 'Gain a Alien Technology (yellow) die into your Citizenry when you place this world.',
    ONE_YELLOW_DIE_TO_WORLD: 'Gain an Alien Technology (yellow) good on this world when you place it.',
    REBEL_MINERS: 'Remove any one of your dice, then gain two Military (red) dice into your citizenry.',
    REBEL_WARRIOR_RACE: 'Remove any one of your dice and gain a Military (red) and a Genes (green) die into your Citizenry when you place this world.',
    REMOVE_ONE_DIE_AND_ONE_RED_DIE_TO_CUP: 'Remove any one of your dice and gain a Military (red) die into your cup when you place this world.',
    SPACE_MARINES: 'Remove any one of your dice, then gain $1 and a Military (red) die into your cup.',
    THREE_CREDITS_AND_ONE_YELLOW_DIE_TO_CUP: 'Gain $3 and an Alien Technology (yellow) die into your cup when you place this world.',
    TWO_CREDITS_AND_ONE_YELLOW_DIE_TO_CUP: 'Gain $2 and an Alien Technology (yellow) die into your cup when you place this world.',
    TWO_CREDITS_AND_ONE_YELLOW_DIE_TO_WORLD: 'Gain $2 and a Alien Technology (yellow) good on this world when you place it.',
    TWO_CREDITS_AND_ONE_PURPLE_DICE_TO_CITIZENRY: 'Gain $2 and one Consumption (purple) die into your Citizenry when you place this world.',
    TWO_CREDITS_AND_TWO_PURPLE_DICE_TO_CITIZENRY: 'Gain $2 and two Consumption (purple) dice into your Citizenry when you place this world.',
    TWO_RED_DICE_TO_CITIZENRY: 'Gain two Military (red) dice into your Citizenry when you place this world.'
};

export const developmentPowers = {
    ADVANCED_LOGISTICS: 'You may rearrange all tiles in your construction zone (including turning them over)',
    ALIEN_ARCHAEOLOGY: '+$4 (instead of +$2) when Stocking with an Alien Technology (yellow) explorer.',
    ALIEN_RESEARCH_SHIP: 'Act as if your had an extra Home (white) explorer and an extra Alien Technology (yellow) explorer for use this phase.',
    ALIEN_RESEARCH_TEAM: 'Draw and keep an extra tile at the end of this phase. If you Scouted with at least one Alien Technology (yellow) explorer, +$1.',
    ALIEN_UPLIFT_BLUEPRINTS: 'Genes (green) and Alien Technology (yellow) worlds require one fewer settler to complete.',
    BACKUP_PLANNING: 'In the same round, you may Dictate more than once to Reassign workers.',
    BIOLOGICAL_ADAPTATION: 'All Reassign-power developments require one fewer developer to complete (but no fewer than one).',
    COLONIAL_AFFINITY: 'You may Reassign one worker to become a settler.',
    CONSUMER_MARKETS: '+$1 for each good on a Novelty (blue) world at the end of this phase.',
    DIVERSIFICATION: 'You may Reassign one Home (white) explorer to any phase.',
    EXECUTIVE_POWER: 'You may Reassign exactly two same-phase workers to the phase you select.',
    EXPORT_DUTIES: '+$1 for each good you Trade this phase.',
    FREE_TRADE_ASSOCIATION: '+$2 at the end of this phase.',
    FREE_TRADE_ASSOCIATION_ENDGAME: 'Add half of your total Novelty (blue) world cost (rounded up).',
    FREE_TRADE_ZONE: 'Grey worlds require two fewer settlers to complete (but no fewer than two).',
    GALACTIC_BANKERS: 'Each time you Trade a good this phase, you may spend $1 to gain 1VP chip.',
    GALACTIC_BANKERS_ENDGAME: '+1 VP per development in your tableau',
    GALACTIC_DEMAND: '+$2 for each good you Trade this turn from a Novelty (blue) world.',
    GALACTIC_EXCHANGE: 'When completing each world, put one or two of the settlers used into your cup instead of your Citizenry.',
    GALACTIC_EXCHANGE_ENDGAME: '+1 VP for each different color of dice you own.',
    GALACTIC_FEDERATION: 'When completing each development (after this one), put one or two of the developers used into your cup instead of your Citizenry.',
    GALACTIC_FEDERATION_ENDGAME: 'Add one-third of your total base development cost (rounded up).',
    GALACTIC_INFLUENCE: 'You may Reassign one worker to any phase.',
    GALACTIC_INVESTORS: '+$2 at the end of this phase, including the phase in which you complete this.',
    GALACTIC_MANDATE: 'When using Dictate, you may Reassign up to three (not one) other workers to any phase(s).',
    GALACTIC_RECYCLING: '+$1 after completing each development or world, not including this one.',
    GALACTIC_RELIGION: '+$1 for each Novelty (blue) die in your Citizenry at the end of this phase.',
    GALACTIC_RENAISSANCE: '+1 VP chip for each good you Consume this phase.',
    GALACTIC_RENAISSANCE_ENDGAME: '+1, 2, 3, 4, ... VP for 1, 3, 6, 10, ... VP in chips.',
    GALACTIC_RESERVES: 'Each of your worlds can hold an extra good (each good still requires 1 shipper).',
    GALACTIC_RESERVES_ENDGAME: '+1 VP per good (at the end of the game).',
    GALACTIC_SALON: 'Gain 1 VP chip.',
    GENETICS_LAB: '+$2 for each good represented by a Genes (green) die at the end of this phase.',
    HOMEWORLD_PATRIOTISM: 'You may Reassign one or two Home (white) workers to the phase you select.',
    HYDROPONICS_GUILD: 'You may Reassign one Novelty (blue) or Genes (green) worker to any phase.',
    IMPROVED_RECONNAISSANCE: 'You may place new tiles on top of your stacks when Scouting.',
    INVESTMENT_CREDITS: 'All developments (after this one) require one fewer developer to complete (but not fewer than one).',
    ISOLATION_POLICY: 'You may Reassign one or two explorers to any phase(s).',
    JUMPDRIVE_RESEARCH: '+1$ for each good you Trade this turn from a Rare Elements (brown) world.',
    LOCAL_SUBSIDIES: 'You may Reassign one Home (white) worker to any phase.',
    MAD_SCIENTISTS: 'If you have the most Novelty (blue) worlds in tableau you may Reassign one or two workers to any phase(s). (If tied, you may Reassign one.)',
    MAJOR_RESEARCH_LABS: 'Act as if you have an extra Home (white) explorer for use this phase.',
    MERCHANT_GUILD: '+$2 at the end of this phase.',
    MINING_INDUSTRY: '+$1 for each good you Consume (not Trade) this phase from a Rare Elements (brown) world.',
    MINING_LEAGUE: '+$1 for each good on a Rare Elements (brown) world at the end of this phase.',
    MINING_LEAGUE_ENDGAME: '+2 VP per Rare Elements (brown) world in your tableau.',
    MINOR_RESEARCH_LABS: '+1 VP chip for each good you Consume from a Genes (green) or Alien Technology (yellow) world this phase.',
    NANOTECHNOLOGY: 'You may Reassign one or two workers to any phase(s).',
    NEW_ECONOMY: '+$2 for each good you Consume this phase.',
    NEW_ECONOMY_ENDGAME: '+1 VP per development without a Reassign power (including this one).',
    NEW_GALACTIC_ORDER: 'When completing each world, put all of the Military (red) settlers used into your cup instead of your Citizenry.',
    NEW_GALACTIC_ORDER_ENDGAME: '+2 VP per 3 Military (red) dice you own (rounded up).',
    OPERATIONS_AFFINITY: 'You may Reassign one worker to become an explorer or a producer.',
    ORGANIC_SHIPYARDS: 'Act as if you have an extra Home (white) shipper and an extra Genes (green) shipper for use this phase.',
    PROPAGANDA_CAMPAIGN: 'You may Reassign one or two workers to the phase you select.',
    PUBLIC_WORKS: '+$1 after completing each development (other than this one).',
    REPLICANT_ROBOTS: 'All worlds require one fewer settler to complete (but not fewer than one).',
    ROBOT_SURVEYORS: '+$2 at the end of this phase.',
    SHIPPING_AFFINITY: 'You may Reassign one worker to become a shipper.',
    SPACE_DOCKS: 'Act as if you have one more Home (white) shipper for use this phase.',
    SPACE_MERCENARIES: 'You may Reassign one Military (red) or Rare Elements (brown) worker to any phase.',
    SPACE_PIRACY: '+$1 for every two Military (red) dice (rounded up) in your Citizenry at the end of the phase.',
    SPACE_REFINERIES: '+1 VP chip for each good you Consume from a Rare Elements (brown) world this phase.',
    SPACE_TOURISM: '+$1. If you have the highest-cost world(s) across all tableaus, +$1 extra.',
    SYSTEM_DIVERSIFICATION: 'You may Reassign one or two non-Home (non-white) workers to any phase(s).',
    TECHNOLOGY_AFFINITY: 'You may Reassign one worker to become a developer.',
    TECHNOLOGY_UNIONS: '+$1 if you have the most developments in tableau. (If tied for most you do not get anything.)',
    TERRAFORMING_ROBOTS: '$1 after completing any world. If completing a Rare Elements (brown) world, +$1 extra.',
    TRADE_LEVIES: '+$1 for each good you Consume this phase.'
};
